CREATE TABLE plans
(
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(256) NOT NULL,
  description VARCHAR(256),
  startDay DATE NOT NULL,
  startTime TIME NOT NULL,
  endDay DATE NOT NULL,
  endTime TIME NOT NULL
);